add full 2023 roster, add a bunch of pictures
brendanwallace/switchbackultimate.github.io pull request #17
Opened 2023-08-04 23:24 UTC by a14glick

Finally Updated! Still need some pictures.

2023-08-08 18:58 UTC, brendanwallace requested changes
It all looks good except for the unnecessary changes to _index.md!

2023-08-08 18:58 UTC, brendanwallace commented on content/roster/2023/_index.md
> +#### Captain:
these changes don't do anything (this stuff is the "content" of the _index page but I'm not actually using it in the rendering)

please delete from #### Captain: onwards

2023-08-08 18:58 UTC, brendanwallace commented on layouts/roster/roster.html
> +
nice :)

2023-08-09 00:21 UTC, a14glick commented on layouts/roster/roster.html
> +
thank!

2023-08-09 19:02 UTC, brendanwallace approved these changes
LGTM

2023-08-09 19:12 UTC, merged